[phases.setup]
nix_pkgs = ["gcc", "libffi", "openssl", "zlib", "python3Distutils"]

[phases.install]
cmd = "pip install --upgrade pip && pip install -r requirements.txt"

[start]
cmd = "gunicorn app:app"
